### ISSUE TITLE
process.stdout.clearLine is not a function

### ISSUE THREAD

**Issue by firdiar** [Briuor/wbm#27]
Authenticating...
TypeError: process.stdout.clearLine is not a function
    at sendTo (D:\Work\Gtion\DiscordBotSimple\node_modules\wbm\src\api.js:170:24)
    at async Object.send (D:\Work\Gtion\DiscordBotSimple\node_modules\wbm\src\api.js:184:9)
    at async D:\Work\Gtion\DiscordBotSimple\index.js:59:3

im trying to make a simple bot integrated from discord to WA

**Comment by balataca** [comment]
Try to edit this file `node_modules/wbm/src/api.js` with the contents of this gist. Please let me know if it works so I can make a PR.

https://gist.github.com/balataca/3db96827cd114aa0cec1763f58eef4e6
